### ISSUE TITLE
Changing MQTT_CLIENT_ID may overwrite SSID

### ISSUE THREAD

**Issue by StefanBruens** [tuanpmt/esp_mqtt#108]
modules/config.c lacks any length checks. As sysCfg.device_id is copied after sysCfg.ssid, device_id may actually overwrite ssid.

I accidentally changed MQTT_CLIENT_ID to to be exactly 16 characters after expanding the format string, thus the terminating \0 became the first character of the ssid.

**Comment by tuanpmt** [comment]
I was remove config module in develop branch, and will merge into the master soon.
