### ISSUE TITLE
Flash to esp

### ISSUE THREAD

**Issue by panagorn** [tuanpmt/esp_mqtt#113]
Hello i am new to esp8266 module. I want to ask how to flash this to esp module and how to connect esp with the pc. Thank you

**Comment by sreeisalso** [comment]
Check the [Readme](https://github.com/tuanpmt/esp_mqtt/blob/master/README.md) file everything is there

Regards
Sreekanth

**Comment by tuanpmt** [comment]
There are many tutorial about it, this project only focus to mqtt protocol
