### ISSUE TITLE
Updated ESP_MQTT

### ISSUE THREAD

**Issue by tuanpmt** [tuanpmt/esp_mqtt#119]
Hello everyone,
Sorry for Boom mail, I have closed many issues and expected to plan to resolve others. But we have some news:
- esp_mqtt was updated to work with SDK 2.0
- Makefile was cleaned up and easy to use, but need to improve to use with fota firmware 
- Remove esptool submodule (you need to clone from official project)
- Reformat code
- Fix issue call connected callback before disconnect if mqtt username and password not correct 
- Remove `config` module, simplifying the use
- Using `user_config.local.h` to avoid provide Wifi information to github

Thank you,

**Comment by tuanpmt** [comment]
@vowstar You really contributed a lot to this project. Please help me noticed changes affect not good

**Comment by harryd100** [comment]
Great, just converted one of my existing projects to the latest build and SDK 2.0.0. Works fine.

**Comment by vowstar** [comment]
@tuanpmt Ok, I will notice and test these changes on amount of hardware, I'm trying to build a statistical platform to do this.
