### ISSUE TITLE
Error with comport window 

### ISSUE THREAD

**Issue by maiminhtien94** [tuanpmt/esp_mqtt#122]
I have edit comport in makefile to same as comport in device manager but when i flash it not work and console. I did  set the ESP8266 to firmware mode (GIO0 = High during boot) .
![image](https://cloud.githubusercontent.com/assets/20992946/19412283/9b6e8acc-933c-11e6-8852-88732313556c.png)
![image](https://cloud.githubusercontent.com/assets/20992946/19412290/dbd56e14-933c-11e6-8f73-e2539e850cfc.png)
![image](https://cloud.githubusercontent.com/assets/20992946/19412305/4ffab9fc-933d-11e6-9717-e74e571f1228.png)

**Comment by tuanpmt** [comment]
This is an issue of Python Serial on Windows, please check your python version and test with esptool.py before

**Comment by maiminhtien94** [comment]
thanks you!
