### ISSUE TITLE
mqttPublished callback is not getting called

### ISSUE THREAD

**Issue by betgear** [tuanpmt/esp_mqtt#13]
When publishing a message, the mqttPublished callback is not getting called. Using the latest code with the mqttpublish in the connected callback (fix works, thanks), the INFO("MQTT: Published\r\n"); message is never displayed.

MQTT: Send mqtt connection info, to broker 192.168.1.147:1883
TCP: Sent
TCP: data received
MQTT: Connected to 192.168.1.147:1883
TCP: Sent
TCP: data received
MQTT: Subscribe successful
TCP: Sent
TCP: data received
MQTT: Connected
MQTT: sending publish...
MQTT: Subscribe successful
TCP: Sent
TCP: data received
TCP: Sent
TCP: data received
TCP: data received
MQTT topic: /test/topic, data: Hello World
MQTT: sending publish...
TCP: Sent

MQTT: Send keepalive packet to 192.168.1.147:1883!
TCP: Sent
TCP: data received

Surely we should see an MQTT: Published message after the TCP:Sent message?

**Comment by tuanpmt** [comment]
please check for lasted commit: 9698516f1e717cfaf641adc32988227fea60ea16
