### ISSUE TITLE
Reconnecting but not RE-subscribing when broker goes down

### ISSUE THREAD

**Issue by Werquinx** [tuanpmt/esp_mqtt#15]
When I purpously disconnect the broker and then bring it back up, the ESP8266 will automatically reconnect to the broker, but the subscriptions are lost and hence will not receive any messages anymore.
Is there a call back where I should re-subscribe when the ESP is automatically re-connecting ?

Thanks.

**Comment by tuanpmt** [comment]
Uhm, i think the problem is: *MQTT_Subscribe* called in *wifiConnectCb*, i need to move it to *mqttConnectedCb*.
Thanks
