### ISSUE TITLE
sta_pwd in user_config.h is too smal

### ISSUE THREAD

**Issue by struhalla** [tuanpmt/esp_mqtt#18]
it would be fine if the field sta_pwd in user_config.h can be increased to 64 Bytes, as it is too small for long WPA2 pass phrases. 
If it is not possible please give a warning on too long values for the string parameters.

**Comment by Diaoul** [comment]
I read everywhere that maximum length for WPA2 passwords is 64 bytes. Where did you get the information that it could be more?

**Comment by struhalla** [comment]
In struct syscfg (config.h) the field for the stored password is limited 32 Bytes. This should be 64, to allow long WPA2 passwords.
