### ISSUE TITLE
Queue not working

### ISSUE THREAD

**Issue by scargill** [tuanpmt/esp_mqtt#24]
HI

Not sure if there is supposed to be a publish queue but if not is there a chance you could fix this please... sometimes I need to be able to send 2 messages, one after another - and I can't as only the last one gets through as if the first is being over-written. Would REALLY appreciate this?

**Comment by scargill** [comment]
I just thought of another reason we need the queue working - one ESP8266 might have several functions - I want to send a temperature message to openHab and also a humidity message -  I can't send them both in the same message - so I have to send 2 - which right now means staggering them and that doesn't work well if I've had a request from the syttem for that data - we could of course implement this in a timer but seems so daft if it's supposed to be there? Is the queue supposed to work?

**Comment by scargill** [comment]
Cannot get mqttPublishedCb to fire at end of a publication

**Comment by betgear** [comment]
Hi Peter,

Get the latest version of the code, I believe it's fixed in that.

Cheers

Glen.

**Comment by scargill** [comment]
Indeed it is and I’ve implemented a working queue until the real one comes along – together with RTC. More at http://scargill.wordpress.com

**Comment by scargill** [comment]
Oh excellent.

**Comment by scargill** [comment]
Sent time to 3 publications one after another – and the software crashed. First time I’ve seen it crash.

**Comment by mhwlng** [comment]
I pusblish one string, every minute.
now the data for the first publish is re-used every time, instead of using the new data.

**Comment by scargill** [comment]
Hi

 

I just wasted ages thinking your new code was broken – then tried my own queue and that broke to – after a lot of wasted time.. it hit me…

 

If the ESP8266 is subscribed to a topic – and someone publishes the topic with NO MESSAGE (I’m using MQTT-SPY) the program crashes.  I think it would be well worthwhile trapping this and making sure it treats this as an empty message.

 

With data in the message

 

TCP: data received

MQTT topic: myleds, data: {0} 

MQTT: sending publish...

TCP: Sent

MQTT: Published

 

With an empty message

 

TCP: data received

Fatal exception (28):

epc1=0x4000df7c, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

rm match

pm close 7 0 0/163406647

 

ets Jan  8 2013,rst cause:4, boot mode:(3,7)

 

wdt reset

load 0x40100000, len 31624, room 16 

tail 8

chksum 0xec

load 0x3ffe8000, len 2652, room 0 

tail 12

chksum 0xfa

ho 0 tail 12 room 4

load 0x3ffe8a60, len 7408, room 12 

tail 4

chksum 0x4c

**Comment by tuanpmt** [comment]
I've checked very carefully, it still worked fine. Have you checkout the latest code version yet?

**Comment by scargill** [comment]
I downloaded a version yesterday and I am using that. But exactly the same happens with much earlier versions.

 

I can do this 100% repeatedly – see my code above… your code – I’ve added my stuff in. 

 

So I have 4 topics – I’ve added some real time clock (1 second interrupt) – I check for “time” every 5 seconds and update a single LONG in the interrupt… temperature sensor (does not matter if it is not plugged into GPIO2) – LEDS are GPIO0 – again does not matter if not plugged in.

 

The point being – it is utterly reliable as long as there is something send in the message from MQTT-SPY – but EVERY time I leave the message empty – it crashes – both my original version where I wrote the queue and your new one.

 

In the code you will easily see my added code – for temperature sensor (DHT22) – real time clock (a simple LONG incremented every second – and code to fill a struct with time and date) and some port IO (feel free to use anything – but warning the WS2812B code does not work due to compiler issues- need someone to write a little bit of it in assembler).

 

 <https://code.google.com/p/mqtt-spy/> https://code.google.com/p/mqtt-spy/

**Comment by tuanpmt** [comment]
Ok, problem is empty data, but queue is working rightnow ?

**Comment by scargill** [comment]
Oh yes, queue is working perfectly – but BOTH the version BEFORE the queue and AFTER the queue fail with empty data…  must be worth a quick fix?

**Comment by tuanpmt** [comment]
Yup,
That is another issue opening #19
