### ISSUE TITLE
make ssl optionnal ?

### ISSUE THREAD

**Issue by mhwlng** [tuanpmt/esp_mqtt#29]
Could you please add an #ifdef around each espconn_secure_.. functions in mqtt.c

I'm running out of memory (esphttpd + mqtt + DS18B20 + ntp client)

Currently:
0x00000.bin   -> 41KB
0x40000.bin   -> 172KB

After I comment out all the espconn_secure_... functions in mqtt.c :
0x00000.bin   -> 38KB
0x40000.bin   -> 144KB

I didn't have to remove ssl from the LIBS statement in the makefile.

**Comment by scargill** [comment]
Do we REALLY have to waste all that space down at the bottom? Would it not make sense to start at zero, have all that space available and put the config at the very top?  I'm not a real expert at this yet but I'm fairly sure most of the space at 00000 is not being used...
