### ISSUE TITLE
Compilation and running

### ISSUE THREAD

**Issue by scargill** [tuanpmt/esp_mqtt#3]
Hi

Two of us on two completely separate systems have updated to your new code.  Firstly once you compile and flash a chip - next time you compile and flash, there is no difference  even though the BIN files have been updated. Something wrong there.  I can guarantee that the ESP-01 will not be getting the update even though it looks as it it has programmed.

Secondly when we power up with the updated software, we don't seem to get the little progress dots any more,. That is as far as we have gone.

**Comment by tuanpmt** [comment]
Hello scargill,
I believe that the information you received in the last few days has solved this problem.

**Comment by scargill** [comment]
Yes, it looks all resolved. Well done. Now to start making use.
