### ISSUE TITLE
Problems ubdating

### ISSUE THREAD

**Issue by aidanruff** [tuanpmt/esp_mqtt#4]
Hi
I managed to install the new version of your MQTT software thanks. However, one you install one version you cannot then install another one. The .bin files are being generated and apparently uploaded correctly.

I think that there's a problem in the makefile. 

Your earlier version 'flash_ota_boot' had this:-
$(PYTHON) $(ESPTOOL) -p $(ESPPORT) write_flash 0x00000 $(BOOTLOADER) 0x01000 firmware/user1_0x01000.bin 0x11000 firmware/user1_0x11000.bin 0x7E000  $(BLANKER)

and your new one does this:-
$(PYTHON) $(ESPTOOL) -p $(ESPPORT) write_flash 0x00000 firmware/0x00000.bin 0x40000 firmware/0x40000.bin

I suspect that this is the code for the cloud update version which would, I guess be loaded into flash and verified before the restart vector was set to avoid corrupting the software if there was a transmission error.

I'm guessing that what's happening is that the current makefile is just dumping subsequent software updates into flash into a location relative to the previous one but not changing the restart vector - instead of putting it on top of the bootloader?

Maybe!

**Comment by eadf** [comment]
There is a #define CFG_HOLDER in user_config.h that caused some similar problems for me. 
As long as the value of that #define is identical to what's already in the flash memory the new settings will not be used.

**Comment by aidanruff** [comment]
AH, that’s interesting! So, do you think that you need to change that every time to allow any updated software to run?

I’m using you’re original Make file with the addition of the SSL library and it works fine – a little less elegant that your more recent one, but it works fine.

What do you think of my suggestions regarding a final format for the serial comms and a wifi/web page for initial setup of the ESP modules? I think that it would make the module really usable.

I have a number of holiday properties that I’d like to add remote controlled mains devices to and the ESP module with some support hardware would work together wonderfully.

I’m using RabbitMQ as a broker and I can foresee writing some sort of PHP based web control software to do overall control

Kind Regards

Aidan
