### ISSUE TITLE
Time to ditch esptool?

### ISSUE THREAD

**Issue by eadf** [tuanpmt/esp_mqtt#41]
The easiest way of building the toolchain seems to be: https://github.com/pfalcon/esp-open-sdk
But that package does not build esptool, instead it expects us to use epstool.py.

esptool.py can not only flash the esp, but also create the .bin files we need when flashing.

I've made a makefile that [uses esptool.py instead of esptool.](https://github.com/eadf/esp_mqtt_lcd)
Yes, it's the old mqtt makefile :)

The only problem is that esptool.py creates the *.bin* files in the same directory it finds the *elf* file in. So instead of moving files around i removed the *firmware* folder and instead put everything inside *build*.

I could make a pull request if you like, but I've made some other changes to the makefile as well, so maybe it's best if you just copy&paste whatever you like. If you want to ditch esptool at all, that is..

**Comment by tuanpmt** [comment]
hello eadf,
please make PR to help us making it better.
Thanks
