### ISSUE TITLE
MQTT witch OTA

### ISSUE THREAD

**Issue by styszkiew** [tuanpmt/esp_mqtt#42]
This great but I can not get a library MQTT cope with OTA in the make file "ERROR build / app.out1 section` .irom0.text 'will not fit in the region `irom0_0_seg' 'if you can show your solution.

**Comment by tuanpmt** [comment]
Need more info

**Comment by styszkiew** [comment]
I wanted to add to the MQTT SUPPORT FOR OTA but I still do not know how to add the makefile productions user1.bin
my makefile looks like this:
BUILD_BASE	= build
FW_BASE		= firmware
FLAVOR = release
#FLAVOR = debug

# Base directory for the compiler
XTENSA_TOOLS_ROOT ?=  c:/Espressif/xtensa-lx106-elf/bin

# base directory of the ESP8266 SDK package, absolute
SDK_BASE	?= c:/Espressif/ESP8266_SDK_093

#Esptool.py path and port
PYTHON		?= C:/Python27/python.exe
SDK_TOOLS	?= c:/Espressif/utils
ESPTOOL		?= $(SDK_TOOLS)/esptool.exe
ESPPORT		?= COM2

JOIN_TOOL ?= $(SDK_BASE)/tools/gen_flashbin.py

WEB_DIR ?=C:\Espressif\examples\ota_test\www\htdocs\v1\device\rom

# name for the target project
TARGET		= app

# which modules (subdirectories) of the project to include in compiling
MODULES		= driver mqtt user user/chip user/io
EXTRA_INCDIR    = include $(SDK_BASE)/../include

# libraries used in this project, mainly provided by the SDK
LIBS		= c gcc hal phy pp net80211 lwip wpa upgrade main ssl

# compiler flags using during compilation of source files
CFLAGS		= -Os -Wpointer-arith -Wundef -Werror -Wl,-EL -fno-inline-functions -nostdlib -mlongcalls -mtext-section-literals  -D__ets__ -DICACHE_FLASH

# linker flags used to generate the main object file
LDFLAGS		= -nostdlib -Wl,--no-check-sections -u call_user_start -Wl,-static

ifeq ($(FLAVOR),debug)
    CFLAGS += -g -O2
    LDFLAGS += -g -O2
endif

ifeq ($(FLAVOR),release)
    CFLAGS += -g -O0
    LDFLAGS += -g -O0
endif

# linker script used for the above linkier step
LD_SCRIPT	= eagle.app.v6.ld
LD_SCRIPT1	= eagle.app.v6.app1.ld
LD_SCRIPT2	= eagle.app.v6.app2.ld

# various paths from the SDK used in this project
SDK_LIBDIR	= lib
SDK_LDDIR	= ld
SDK_INCDIR	= include include/json

# we create two different files for uploading into the flash
# these are the names and options to generate them
FW_FILE_1	= 0x00000
FW_FILE_1_ARGS	= -bo $@ -bs .text -bs .data -bs .rodata -bc -ec
FW_FILE_2	= 0x40000
FW_FILE_2_ARGS	= -es .irom0.text $@ -ec

FW_FILE_3	= user1
FW_FILE_4	= user2

#Intermediate files for User1.bin and User2.bin
FW_INTF_1	= 0x01000
FW_INTF_1_ARGS	= -bo $@ -bs .text -bs .data -bs .rodata -bc -ec

FW_INTF_2	= 0x11000
FW_INTF_2_ARGS	= -es .irom0.text $@ -ec

FW_INTF_3	= 0x41000
FW_INTF_3_ARGS	= -bo $@ -bs .text -bs .data -bs .rodata -bc -ec

FW_INTF_4	= 0x51000
FW_INTF_4_ARGS	= -es .irom0.text $@ -ec


# select which tools to use as compiler, librarian and linker
CC		:= $(XTENSA_TOOLS_ROOT)/xtensa-lx106-elf-gcc
AR		:= $(XTENSA_TOOLS_ROOT)/xtensa-lx106-elf-ar
LD		:= $(XTENSA_TOOLS_ROOT)/xtensa-lx106-elf-gcc

####
#### no user configurable options below here
####
FW_TOOL		?= $(XTENSA_TOOLS_ROOT)/esptool

SRC_DIR		:= $(MODULES)
BUILD_DIR	:= $(addprefix $(BUILD_BASE)/,$(MODULES))

SDK_LIBDIR	:= $(addprefix $(SDK_BASE)/,$(SDK_LIBDIR))
SDK_INCDIR	:= $(addprefix -I$(SDK_BASE)/,$(SDK_INCDIR))

SRC		:= $(foreach sdir,$(SRC_DIR),$(wildcard $(sdir)/*.c))
OBJ		:= $(patsubst %.c,$(BUILD_BASE)/%.o,$(SRC))
LIBS		:= $(addprefix -l,$(LIBS))
APP_AR		:= $(addprefix $(BUILD_BASE)/,$(TARGET)_app.a)
TARGET_OUT	:= $(addprefix $(BUILD_BASE)/,$(TARGET).out)

LD_SCRIPT	:= $(addprefix -T$(SDK_BASE)/$(SDK_LDDIR)/,$(LD_SCRIPT))
LD_SCRIPT1	:= $(addprefix -T$(SDK_BASE)/$(SDK_LDDIR)/,$(LD_SCRIPT1))
LD_SCRIPT2	:= $(addprefix -T$(SDK_BASE)/$(SDK_LDDIR)/,$(LD_SCRIPT2))

INCDIR	:= $(addprefix -I,$(SRC_DIR))
EXTRA_INCDIR	:= $(addprefix -I,$(EXTRA_INCDIR))
MODULE_INCDIR	:= $(addsuffix /include,$(INCDIR))

FW_FILE_1	:= $(addprefix $(FW_BASE)/,$(FW_FILE_1).bin)
FW_FILE_2	:= $(addprefix $(FW_BASE)/,$(FW_FILE_2).bin)
FW_FILE_3	:= $(addprefix $(FW_BASE)/,$(FW_FILE_3).bin)
FW_FILE_4	:= $(addprefix $(FW_BASE)/,$(FW_FILE_4).bin)

FW_INTF_1	:= $(addprefix $(FW_BASE)/,$(FW_INTF_1).bin)
FW_INTF_2	:= $(addprefix $(FW_BASE)/,$(FW_INTF_2).bin)
FW_INTF_3	:= $(addprefix $(FW_BASE)/,$(FW_INTF_3).bin)
FW_INTF_4	:= $(addprefix $(FW_BASE)/,$(FW_INTF_4).bin)

V ?= $(VERBOSE)
ifeq ("$(V)","1")
Q :=
vecho := @true
else
Q := @
vecho := @echo
endif

vpath %.c $(SRC_DIR)

define compile-objects
$1/%.o: %.c
	$(vecho) "CC $$<"
	$(Q) $(CC) $(INCDIR) $(MODULE_INCDIR) $(EXTRA_INCDIR) $(SDK_INCDIR) $(CFLAGS)  -c $$< -o $$@
endef

.PHONY: all checkdirs clean

all: checkdirs $(TARGET_OUT) $(FW_FILE_1) $(FW_FILE_2) $(FW_FILE_3) $(FW_FILE_4)

$(FW_FILE_1): $(TARGET_OUT)
	$(vecho) "FW $@"
	$(Q) $(FW_TOOL) -eo $(TARGET_OUT) $(FW_FILE_1_ARGS)

$(FW_FILE_2): $(TARGET_OUT)
	$(vecho) "FW $@"
	$(Q) $(FW_TOOL) -eo $(TARGET_OUT) $(FW_FILE_2_ARGS)


$(FW_FILE_3): $(FW_INTF_1) $(FW_INTF_2)
	@echo "FW $@"
	@$(PYTHON) $(JOIN_TOOL) $(FW_INTF_1) $(FW_INTF_2)
#	@echo "EW2 $@"
	@mv eagle.app.flash.bin $@
	@cp $@ $(WEB_DIR)

$(FW_FILE_4): $(FW_INTF_3) $(FW_INTF_4)
	@echo "FW $@"
	@$(PYTHON) $(JOIN_TOOL) $(FW_INTF_3) $(FW_INTF_4)
	@mv eagle.app.flash.bin $@
	@cp $@ $(WEB_DIR)

#Intermediate bin files for User1 and User2

$(FW_INTF_1): $(TARGET_OUT)
	@echo "FW $@"
	@$(FW_TOOL) -eo $(TARGET_OUT)1 $(FW_INTF_1_ARGS)

$(FW_INTF_2): $(TARGET_OUT)
	@echo "FW $@"
	@$(FW_TOOL) -eo $(TARGET_OUT)1 $(FW_INTF_2_ARGS)

$(FW_INTF_3): $(TARGET_OUT)
	@echo "FW $@"
	@$(FW_TOOL) -eo $(TARGET_OUT)2 $(FW_INTF_3_ARGS)

$(FW_INTF_4): $(TARGET_OUT)
	@echo "FW $@"
	@$(FW_TOOL) -eo $(TARGET_OUT)2 $(FW_INTF_4_ARGS)


$(TARGET_OUT): $(APP_AR)
	$(vecho) "LD $@"
	$(Q) $(LD) -L$(SDK_LIBDIR) $(LD_SCRIPT) $(LDFLAGS) -Wl,--start-group $(LIBS) $(APP_AR) -Wl,--end-group -o $@
	@$(LD) -L$(SDK_LIBDIR) $(LD_SCRIPT1) $(LDFLAGS) -Wl,--start-group $(LIBS) $(APP_AR) -Wl,--end-group -o $@1
	@$(LD) -L$(SDK_LIBDIR) $(LD_SCRIPT2) $(LDFLAGS) -Wl,--start-group $(LIBS) $(APP_AR) -Wl,--end-group -o $@2
	
$(APP_AR): $(OBJ)
	$(vecho) "AR $@"
	$(Q) $(AR) cru $@ $^

checkdirs: $(BUILD_DIR) $(FW_BASE)

$(BUILD_DIR):
	$(Q) mkdir -p $@

firmware:
	$(Q) mkdir -p $@

flash: firmware/user1.bin
#	$(ESPTOOL) --port $(ESPPORT) write_flash 0x7e000 $(SDK_BASE)/bin/blank.bin
#	sleep 1
	$(ESPTOOL) --port $(ESPPORT) -b 256000 write_flash 0x00000 firmware/0x00000.bin
	$(ESPTOOL) --port $(ESPPORT) -b 256000 write_flash 0x40000 firmware/0x40000.bin
	sleep 1
	$(ESPTOOL) --port $(ESPPORT) reset

flashota: firmware/user1.bin
	$(ESPTOOL) --port $(ESPPORT) -b 256000 write_flash 0x00000 $(SDK_BASE)/bin/boot_v1.1.bin
	$(ESPTOOL) --port $(ESPPORT) -b 256000 write_flash 0x01000 firmware/user1.bin
	sleep 1	
	$(ESPTOOL) --port $(ESPPORT) reset

flashblank: firmware/user1.bin
	$(ESPTOOL) --port $(ESPPORT) -b 256000 write_flash 0x7e000 $(SDK_BASE)/bin/blank.bin
	sleep 1	
	$(ESPTOOL) --port $(ESPPORT) reset

test: flash
	screen $(ESPPORT) 115200

rebuild: clean all

clean:
	$(Q) rm -f $(APP_AR)
	$(Q) rm -f $(TARGET_OUT)
	$(Q) rm -rf $(BUILD_DIR)
	$(Q) rm -rf $(BUILD_BASE)
	$(Q) rm -f $(FW_FILE_1)
	$(Q) rm -f $(FW_FILE_2)
	$(Q) rm -f $(FW_FILE_3)
	$(Q) rm -f $(FW_FILE_4)
	$(Q) rm -f $(FW_INTF_1)
	$(Q) rm -f $(FW_INTF_2)
	$(Q) rm -f $(FW_INTF_3)
	$(Q) rm -f $(FW_INTF_4)
	$(Q) rm -rf $(FW_BASE)

$(foreach bdir,$(BUILD_DIR),$(eval $(call compile-objects,$(bdir))))

Crashes when compiling error:
make all 
CC driver/uart.c
CC mqtt/config.c
CC mqtt/mqtt.c
CC mqtt/mqtt_msg.c
CC mqtt/proto.c
CC mqtt/queue.c
CC mqtt/ringbuf.c
CC mqtt/utils.c
CC mqtt/wifi.c
CC user/user_main.c
CC user/chip/chipother.c
CC user/chip/dht.c
CC user/chip/ds18b20.c
CC user/chip/work_led.c
CC user/io/io.c
AR build/app_app.a
LD build/app.out
c:/espressif/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: build/app.out1 section `.irom0.text' will not fit in region `irom0_0_seg'
collect2.exe: error: ld returned 1 exit status
make: *** [build/app.out] Error 1

**Comment by tuanpmt** [comment]
When using OTA and booloader then the memory partition only one half. I think your program is too much for that. Please see #31 if your functions not have ICACHE_FLASH_ATTR attribute

**Comment by styszkiew** [comment]
How to compile with the library esp_mqtt to user1.bin it also shows the ".irom0.text' will not fit in regionirom0_0_seg".
What do I have to change in order to compile the esp_mqtt user1.bin?

**Comment by tuanpmt** [comment]
ref: #57
