### ISSUE TITLE
Compile failed on osx.

### ISSUE THREAD

**Issue by crapthings** [tuanpmt/esp_mqtt#47]
10.10.2

make SDK_BASE="/Users/crapthings/hw/esp_iot_rtos_sdk" FLAVOR="release" all
CC driver/uart.c
make: xtensa-lx106-elf-gcc: No such file or directory
make: *** [build/driver/uart.o] Error 1

**Comment by tuanpmt** [comment]
Please add xtensa bin PATH to environment variables
