### ISSUE TITLE
Set device in SoftAP mode when not connected to WIFI

### ISSUE THREAD

**Issue by ghost** [tuanpmt/esp_mqtt#48]
Is it possible to set the device in SoftAP mode when running for the first time. This way we can connect to the device and enter the Wifi details. This would be better because then we don't have to hardcode the wifi details to the device

**Comment by tuanpmt** [comment]
i've try smartconfig from sdk 1.1.0, esptouch 2.1 and esptouch for android 0.3, incredible work. with a button, you can start smart and using phone app for configure ssid and password
