### ISSUE TITLE
error in reading config - ESP8266-01

### ISSUE THREAD

**Issue by terenceang** [tuanpmt/esp_mqtt#51]
My ESP8266-01 won't connect to my AP.

was getting "no 1 found, reconnect after 1s"

Apparently, the "1" is loaded into SSID on CFG_Load(), getting defaults loaded don't seems to work too.
A temp fix is to force the SSID from the header, after the spi reads in CFG_Load.

		os_sprintf(sysCfg.sta_ssid, "%s", STA_SSID);

**Comment by OliverHi** [comment]
I can confirm that problem.

**Comment by tuanpmt** [comment]
when you change default configuration, please change value of CFG_HOLDER, or write blanker value to address 0x3C000

**Comment by georgkreimer** [comment]
What would you set CFG_HOLDER to? Any best practice? I'm using ESP8266 12.

**Comment by tuanpmt** [comment]
any value, it used for check first time write default configuration, if you change it, all values reset to default after esp reset

**Comment by georgkreimer** [comment]
Ok, cool! Just making sure it doesn't write to wrong places ;) Thanks!
