### ISSUE TITLE
Setup development environment

### ISSUE THREAD

**Issue by jdkanani** [tuanpmt/esp_mqtt#55]
Coming from web development, I was wondering how do you setup development environment with this project?

Flashing again and again with small changes seems very difficult. How did you develop this library?

**Comment by tuanpmt** [comment]
yes, this is embedded world, if you don't want this, you can use nodemcu or espruino, using LUA or Javascript for MCU with embedded interpreter flash one time.
I've developed this library by hundred times flashing

**Comment by jdkanani** [comment]
Oh! Thanks for your response.
