### ISSUE TITLE
SSL Turned Off - Constant resets

### ISSUE THREAD

**Issue by betgear** [tuanpmt/esp_mqtt#7]
Hi,

I commented out the CLIENT_SSL_ENABLE line. I changed the port to 1883 and the ESP8266 does not connect correctly to a local MQTT server.

The serial output from the terminal window shows

load ...
MQTT_InitConnection
MQTT_InitClient
WIFI_INIT

System started ...
mode : sta(18:fe:34:98:d5:69)
add if0
scandone
STATION_IDLE
add 0
aid 1
pm open phy_2,type:2 0 0
cnt

connected with betgear, channel 2
dhcp client start...
STATION_IDLE
STATION_IDLE
STATION_IDLE
STATION_IDLE
STATION_IDLE
ip:192.168.1.47,mask:255.255.255.0,gw:192.168.1.1
TCP: Connect to ip  192.168.1.147:1883
MQTT: subscribe, topic"/test/topic" at broker 192.168.1.147:1883
MQTT: subscribe, topic"/test2/topic" at broker 192.168.1.147:1883
client handshake start.
TCP: Reconnect to 192.168.1.147:1883
TCP: Connect to ip  192.168.1.147:1883
TCP:Reconect to: 192.168.1.147:1883
client handshake start.

This is constantly repeating. Whilst the verbose output from Mosquitto shows

1420304463: New connection from 192.168.1.47 on port 1883.
1420304463: Socket error on client (null), disconnecting.
1420304469: New connection from 192.168.1.47 on port 1883.
1420304469: Socket error on client (null), disconnecting.
1420304475: New connection from 192.168.1.47 on port 1883.
1420304475: Socket error on client (null), disconnecting.

Any help appreciated.

Glen.

**Comment by tuanpmt** [comment]
If you don't want to use ssl, in the function MQTT_InitConnection, change security mode to SEC_NONSSL, or 0
