### ISSUE TITLE
Does not connect to Mosquitto broker ?

### ISSUE THREAD

**Issue by Werquinx** [tuanpmt/esp_mqtt#8]
Hi,
Compiled OK and flashed OK.

When running, I get on the ESP8266 side  endless repetition of : 
TCP: Connect to ip  192.168.0.92:1883
TCP:Reconect to: 192.168.0.92:1883
TCP: Reconnect to 192.168.0.92:1883

When I check Mosquitto log, I see repetition of :  
New connection from 192.168.0.31 on port 1883.
Mosquitto socket error on client (null) disconnecting

Any suggestion ???

Thanks.

**Comment by tuanpmt** [comment]
Please post your initialize code

**Comment by Werquinx** [comment]
Actually just resolved ! Your default code uses SSL and my mosquitto server was not configured for SSL. Hence disabled and now everything works OK !!!

Really GOOD !

Thanks.
