### ISSUE TITLE
MQTT Makefile Edits

### ISSUE THREAD

**Issue by storkenterprises** [tuanpmt/esp_mqtt#89]
Upon my first attempt to compile my MQTT code I received a bunch of errors related to the Makefile being unable to find certain files. I changed the following lines:

SDK_BASE	?= /esptools/esp_iot_sdk_v1.3.0
AR = xtensa-lx106-elf-ar
CC = $(TOOLCHAIN)/bin/xtensa-lx106-elf-gcc
LD = xtensa-lx106-elf-gcc
NM = xtensa-lx106-elf-nm
CPP = xtensa-lx106-elf-cpp
OBJCOPY = xtensa-lx106-elf-objcopy

to look like this:

SDK_BASE	?= /ESPTools/esp-open-sdk/esp_iot_sdk_v1.4.0
AR = /ESPTools/esp_mqtt/xtensa-lx106-elf/bin/xtensa-lx106-elf-ar
CC = /ESPTools/esp_mqtt/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc
LD = /ESPTools/esp_mqtt/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc
NM = /ESPTools/esp_mqtt/xtensa-lx106-elf/bin/xtensa-lx106-elf-nm
CPP = /ESPTools/esp_mqtt/xtensa-lx106-elf/bin/xtensa-lx106-elf-cpp
OBJCOPY = /ESPTools/esp_mqtt/xtensa-lx106-elf/bin/xtensa-lx106-elf-objcopy

(Now noticing that I changed the sdk version, which may have been in error.)

Alas! Everything compiled, or seemed to. When I run a make all I now get:

CC driver/uart.c
CC mqtt/mqtt.c
CC mqtt/mqtt_msg.c
CC mqtt/proto.c
CC mqtt/queue.c
CC mqtt/ringbuf.c
CC mqtt/utils.c
CC user/user_main.c
CC modules/config.c
CC modules/wifi.c
AR build/app_app.a
LD build/app.out
FW firmware/0x00000.bin
tools/esptool/esptool.py elf2image build/app.out -o firmware/

When comparing this with the output I get when compiling on my Windows system it looks incomplete. I charged on nonetheless except now it looks like when I update my STA SSID on my mac and recompile it doesn't actually update the firmware flashed to the ESP8266. 

Anyone have any clues as to why I'm getting the truncated feedback during compilation and what I might need to do to fix that? Both firmware bins say they're getting modified when I look at their info but I'm a bit leery that the code isn't getting fully recompiled. Thanks!

**Comment by tuanpmt** [comment]
Please change value of CFG_HOLDER in config.h
