### ISSUE TITLE
little question for uart.

### ISSUE THREAD

**Issue by 12019** [tuanpmt/esp_mqtt#93]
what I want to do is when some chars received from uart0 , then this module sends out like this.

      MQTT_Publish(&mqttClient, "/mqtt/topic/0", "hello9", 6, 0, 0);

but it seems the uart.c file is different. 

question here is 
how do I do to make it work.  and another questions is how can I change uart0 to uart1 for debugging.

void ICACHE_FLASH_ATTR
uart_init(UartBautRate uart0_br, UartBautRate uart1_br)
{
  // rom use 74880 baut_rate, here reinitialize
  UartDev.baut_rate = uart0_br;
  uart_config(UART0);
  UartDev.baut_rate = uart1_br;
  uart_config(UART1);
  ETS_UART_INTR_ENABLE();

  // install uart1 putc callback
  os_install_putc1((void *)uart0_write_char);  <<<< change "uart0" to "uart1" ???
}

**Comment by tuanpmt** [comment]
- Check line 160 and 175 to inject your code
- uart1
