### ISSUE TITLE
Using it with C++

### ISSUE THREAD

**Issue by candale** [tuanpmt/esp_mqtt#95]
Hi,

Any good way to use this library wrapped by a C++ class? I'm having troubles finding ways to register callbacks that are class members and couldn't come up with any good workarounds (I'm not experienced with C++) . Any suggestion is much appreciated.

Thanks.

**Comment by candale** [comment]
I created a simple wrapper over your library. So far it suits my needs, maybe it helps someone else as well: https://github.com/candale/esp_mqt_arduino_wrapper

**Comment by tuanpmt** [comment]
i will add to sample sections in README file,
thanks
